name: Build and Publish Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha,scope=provenance
            *.cache-to=type=gha,scope=provenance,mode=min
        env:
          TAG: v1.0
          REGISTRY: ghcr.io/${{ github.repository_owner }}/
